export const NAVIGATION_DEMO = 'NAVIGATION_DEMO';
export const NAVIGATION_LOGIN = 'NAVIGATION_LOGIN';
export const NAVIGATION_HOME = "NAVIGATION_HOME";
export const NAVIGATION_EDIT = "NAVIGATION_EDIT";